### ISSUE TITLE
[FEATURE REQUEST] reduce misuse of `ObjectImpl::constructed`

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk-rs-core#641] opened 2022-04-10 21:41 UTC
When calling `ObjectImpl::constructed(&self, obj)` the user should remember to call `self.parent_constructed(obj)`.

It's easy to forget it.

I propose adding a parameter:
```rust
fn constructed<F: Fn(obj) -> ()>(&self, obj, parent_constructed: F)
```
so that the required usage of `parent_constructed` is encoded by the type system.

**Comment by bilelmoussaoui** [comment] 2022-04-10 21:45
We do that already for dispose, we could do the same here. But i think the issue is it depends on case by case whether you want to chain up at first or at the end

**Comment by ranfdev** [comment] 2022-04-10 21:56
> it depends on case by case whether you want to chain up at first or at the end.

Yeah, the user should be able to choose when to chain up. Adding the function `parent_constructed` as a parameter to `ObjectImpl::constructed` simply signals to the user "Hey, remember you should call this function, it's here for a reason"

**Comment by sdroege** [comment] 2022-04-11 06:31
That seems to complicate the API and add another special case for no good reason. If you have to chain up or not and when is something you always have to think about, and it's the same in basically every other OOP language.

**Comment by sdroege** [comment] 2022-10-10 12:16
Let's close this then

**Closed by sdroege** 2022-10-10 12:16 UTC
Labels: enhancement
