### ISSUE TITLE
[FEATURE REQUEST] downcast/upcast on `Option<Object>`

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk-rs-core#842] opened 2022-12-01 15:22 UTC
There are many cases where gtk returns an `Option<Widget>` which must be downcasted.
Doing `let label: gtk::Label = list_item.child().unwrap().downcast().unwrap();` is not fun (note: `child()` returns `Option<Widget>`).

Implementing downcast and upcast for `Option<Widget>` would remove an `unwrap`.
I think it makes sense. In OOP languages you can have `null` objects, and `null` objects can be downcasted to `null` subclassess, can't they? (Edit: in Java you can upcast a null, but not downcast it. In any case, if we return a Result when downcasting, everything is alright)

**Comment by sdroege** [comment] 2022-12-01 15:23
How about `list_item.child().and_then(|c| child.downcast::<gtk::Label>().ok()).unwrap()`?

**Comment by ranfdev** [comment] 2022-12-01 15:32
That's even longer than before

**Comment by ranfdev** [comment] 2022-12-01 15:34
```rust
// current
let label: gtk::Label = list_item.child().unwrap().downcast().unwrap();
// your solution
let label = list_item.child().and_then(|c| child.downcast::<gtk::Label>().ok()).unwrap()
// with downcast on Option<Object>
let label: gtk::Label = list_item.child().downcast().unwrap();
```

**Comment by bilelmoussaoui** [comment] 2022-12-01 15:55
This is a duplicate of https://github.com/gtk-rs/gtk-rs-core/issues/497

**Closed** 2022-12-04 16:57 UTC
Labels: enhancement
