### ISSUE TITLE
[BUG] `cairo::Context::show_text` panic if text contains NUL byte

### ISSUE THREAD

**Issue by BenjaminRi** [gtk-rs/gtk-rs-core#553] opened 2022-02-16 21:53 UTC
**Bug description**

If we call <a href="https://docs.rs/cairo-rs/latest/cairo/struct.Context.html#method.show_text">`cairo::Context::show_text`</a> with a text string that contains a NUL byte, there is a panic in `cairo` and the application crashes. If we look into the function, it is immediately apparent why:

```
    #[doc(alias = "cairo_show_text")]
    pub fn show_text(&self, text: &str) -> Result<(), Error> {
        unsafe {
            let text = CString::new(text).unwrap();
            ffi::cairo_show_text(self.0.as_ptr(), text.as_ptr())
        };
        self.status()
    }
```

We try to directly construct a `CString` from `text` and `unwrap()` the result. If we call <a href="https://doc.rust-lang.org/std/ffi/struct.CString.html#method.new">`CString::new()`</a> with a string that contains NUL bytes, we get a <a href="https://doc.rust-lang.org/std/ffi/struct.NulError.html">`NulError`</a> which, as can be seen in the snippet above, is simply unwrapped. A user of the `cairo` library is completely unaware of this internal limitation as it is neither documented nor does `show_text` return an error that could be caught.

**Recommended solution**

At the very least, this behavior should be documented, such that people are aware of a possible panic/application crash.

I recommend handing the `NulError` up to the caller or at least return some kind of error to the caller of `show_text`. As an alternative, some handling of strings with NUL inside could be evaluated, but it is unclear to me how such strings should be handled to the full satisfaction of the user.

In the meantime, users can work around this issue simply by avoiding to call this function with Strings that contain a NUL byte. For example, they could filter out the NUL bytes.

**Backtrace**

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(6, [32, 32, 32, 32, 62, 32, 0, 10, 63, 63, 17])', C:\Users\Foo\.cargo\registry\src\github.com-1ecc6299db9ec823\cairo-rs-0.14.0\src\context.rs:692:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\std\src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\core\src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\core\src/result.rs:1613:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src/result.rs:1295:23
   4: cairo::context::Context::show_text
             at C:\Users\Foo\.cargo\registry\src\github.com-1ecc6299db9ec823\cairo-rs-0.14.0\src\context.rs:692:24
   5: sherlog::draw
             at .\src\main.rs:412:3
   6: sherlog::build_ui::{{closure}}
             at .\src\main.rs:1276:40
   7: <O as gtk::auto::widget::WidgetExt>::connect_draw::draw_trampoline
             at C:\Users\Foo\.cargo\registry\src\github.com-1ecc6299db9ec823\gtk-0.14.0\src\auto\widget.rs:3836:13
   [... excess trace cut]
```

**Comment by sdroege** [comment] 2022-02-17 07:18
This is a duplicate of https://github.com/gtk-rs/gtk-rs-core/issues/10

**Closed by sdroege** 2022-02-17 07:18 UTC
Labels: bug
