### ISSUE TITLE
Reorganize for GLib/GIO gir files split

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#1315] opened 2024-02-20 10:49 UTC
UNIX and Win32 APIs are in their own gir files now. Not sure how to best organize that. Probably separate `-sys` crates for them, and have them as `win32` / `unix` submodules in the `glib` crate?

**Comment by bilelmoussaoui** [comment] 2024-02-25 23:16
Duplicate of https://github.com/gtk-rs/gtk-rs-core/issues/1305

**Closed by bilelmoussaoui** 2024-02-25 23:16 UTC
